language: objective-c
osx_image: xcode12
env:
  global:
    - IOS_SDK=iphonesimulator14.0
    - OSX_SDK=macosx11.0
  matrix:
    - SCHEME=HSLuvMac TEST_SDK=$OSX_SDK DESTINATION="arch=x86_64"
    - SCHEME=HSLuviOS TEST_SDK=$IOS_SDK DESTINATION="platform=iOS Simulator,id=F057B777-E0F0-4AD9-B765-796971A7A099,OS=14.0"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -scheme "$SCHEME" -sdk "$TEST_SDK" -destination "$DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c
