language: objective-c
osx_image: xcode7.2
env:
  matrix:
    - SCHEME=HUSLMac TEST_SDK=macosx10.11
    - SCHEME=HUSLiOS TEST_SDK=iphonesimulator
script:
  - xctool -scheme $SCHEME test -test-sdk $TEST_SDK CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
