language: objective-c
osx_image: xcode11.3
env:
  global:
    - IOS_SDK=iphonesimulator13.2
    - OSX_SDK=macosx10.15
  matrix:
    - SCHEME=HSLuvMac TEST_SDK=$OSX_SDK DESTINATION="arch=x86_64"
    - SCHEME=HSLuviOS TEST_SDK=$IOS_SDK DESTINATION="OS=13.2,platform=iOS Simulator,id=8CD72926-1BD5-41EB-9045-03A9239A822F"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -scheme "$SCHEME" -sdk "$TEST_SDK" -destination "$DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c
