name: Test

on:
  - workflow_dispatch
  - pull_request
  - push

jobs:
  test:
    runs-on: macos-13
    strategy:
      matrix:
        params: [ '-scheme HSLuvMac -sdk macosx', '-scheme HSLuviOS -sdk iphonesimulator -destination "platform=iOS Simulator,name:iPhone 14"' ]
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/runner-images/discussions/8367#discussioncomment-12685592
      # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
      - name: Select XCode
        run: sudo xcode-select -s /Applications/Xcode_14.1.app
      - name: Test
        run: xcodebuild ${{ matrix.params }} CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test
